/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import AppPackage.AnimationClass;
import controlador.TextPrompt;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Nico
 */
public class arrendarVehiculo extends javax.swing.JFrame {
    int mouseX;
    int mouseY;
    /**
     * Creates new form Vista2
     */
    public arrendarVehiculo() {
        initComponents();
        
        TextPrompt patenteVehiculo = new TextPrompt("Patente del vehiculo",idVehiculoText);
        TextPrompt rutCliente = new TextPrompt("RUT Cliente",idClienteText);
        TextPrompt estadoVehiculo = new TextPrompt("Estado vehiculo",estadoVehiculoText);
        TextPrompt fechaDeInicio = new TextPrompt("Fecha de inicio",fechaInicioText);
        TextPrompt kilometrajeInicial = new TextPrompt("Kilometraje inicial",kilometrajeInicialText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        botonMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idVehiculoText = new javax.swing.JTextField();
        estadoVehiculoText = new javax.swing.JTextField();
        idClienteText = new javax.swing.JTextField();
        fechaInicioText = new javax.swing.JTextField();
        kilometrajeInicialText = new javax.swing.JTextField();
        botonRealizarArriendo = new javax.swing.JButton();
        MoverVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setForeground(new java.awt.Color(0, 153, 0));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_close_window_50px.png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 40, 40));

        botonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menux64.png"))); // NOI18N
        botonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMenuMouseClicked(evt);
            }
        });
        jPanel2.add(botonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arriendo de vehiculos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1070, -1));

        idVehiculoText.setBackground(new java.awt.Color(51, 153, 255));
        idVehiculoText.setForeground(new java.awt.Color(255, 255, 255));
        idVehiculoText.setBorder(null);
        idVehiculoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idVehiculoTextActionPerformed(evt);
            }
        });
        jPanel2.add(idVehiculoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 360, 40));

        estadoVehiculoText.setBackground(new java.awt.Color(51, 153, 255));
        estadoVehiculoText.setBorder(null);
        estadoVehiculoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoVehiculoTextActionPerformed(evt);
            }
        });
        jPanel2.add(estadoVehiculoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 360, 40));

        idClienteText.setBackground(new java.awt.Color(51, 153, 255));
        idClienteText.setBorder(null);
        idClienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteTextActionPerformed(evt);
            }
        });
        jPanel2.add(idClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 360, 40));

        fechaInicioText.setBackground(new java.awt.Color(51, 153, 255));
        fechaInicioText.setBorder(null);
        jPanel2.add(fechaInicioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 360, 40));

        kilometrajeInicialText.setBackground(new java.awt.Color(51, 153, 255));
        kilometrajeInicialText.setBorder(null);
        kilometrajeInicialText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilometrajeInicialTextActionPerformed(evt);
            }
        });
        kilometrajeInicialText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kilometrajeInicialTextKeyTyped(evt);
            }
        });
        jPanel2.add(kilometrajeInicialText, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 360, 40));

        botonRealizarArriendo.setText("Realizar arriendo");
        jPanel2.add(botonRealizarArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 250, 30));

        MoverVentana.setBackground(new java.awt.Color(102, 51, 255));
        MoverVentana.setForeground(new java.awt.Color(102, 51, 255));
        MoverVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverVentanaMouseDragged(evt);
            }
        });
        MoverVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverVentanaMousePressed(evt);
            }
        });
        jPanel2.add(MoverVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 620));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1320, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1070, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MoverVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MoverVentanaMousePressed

    private void MoverVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMouseDragged
        int cordenadaX = evt.getXOnScreen();
        int cordenadaY = evt.getYOnScreen();

        this.setLocation(cordenadaX-mouseX, cordenadaY-mouseY);
    }//GEN-LAST:event_MoverVentanaMouseDragged

    private void kilometrajeInicialTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kilometrajeInicialTextKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_kilometrajeInicialTextKeyTyped

    private void kilometrajeInicialTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilometrajeInicialTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kilometrajeInicialTextActionPerformed

    private void idClienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteTextActionPerformed

    private void idVehiculoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVehiculoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idVehiculoTextActionPerformed

    private void botonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuMouseClicked
        this.dispose();
        menuAdmin menuAdmn = new menuAdmin();
        menuAdmn.setVisible(true);
    }//GEN-LAST:event_botonMenuMouseClicked

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed

    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked

        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void estadoVehiculoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoVehiculoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoVehiculoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(arrendarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(arrendarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(arrendarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(arrendarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new arrendarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JLabel MoverVentana;
    private javax.swing.JLabel botonMenu;
    private javax.swing.JButton botonRealizarArriendo;
    private javax.swing.JTextField estadoVehiculoText;
    private javax.swing.JTextField fechaInicioText;
    private javax.swing.JTextField idClienteText;
    private javax.swing.JTextField idVehiculoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField kilometrajeInicialText;
    // End of variables declaration//GEN-END:variables
}
