/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.TextPrompt;
import javax.swing.JOptionPane;
/**
 *
 * @author Nico
 */
public class cobranzaVehiculo extends javax.swing.JFrame {
    int mouseX;
    int mouseY;
    /**
     * Creates new form Vista2
     */
    public cobranzaVehiculo() {
        initComponents();
        
        
        TextPrompt idArriendo = new TextPrompt("ID Arriendo",idArriendoText);
        TextPrompt totalNeto = new TextPrompt("Total Neto",netoText);
        TextPrompt iva = new TextPrompt("IVA",ivaText);
        TextPrompt total = new TextPrompt("Total",totalText);
        TextPrompt idEstadoCobranza = new TextPrompt("ID Estado cobranza",idEstadoCobranzaText);  
        TextPrompt fechaRegistro = new TextPrompt("Fecha de registro",fechaRegistroText);
        TextPrompt usuarioRegistro = new TextPrompt("Usuario de registro",usuarioRegistroText);
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        botonMenu = new javax.swing.JLabel();
        tituloCobranzaArriendo = new javax.swing.JLabel();
        idArriendoText = new javax.swing.JTextField();
        netoText = new javax.swing.JTextField();
        ivaText = new javax.swing.JTextField();
        totalText = new javax.swing.JTextField();
        idEstadoCobranzaText = new javax.swing.JTextField();
        fechaRegistroText = new javax.swing.JTextField();
        usuarioRegistroText = new javax.swing.JTextField();
        botonRealizarCobranza = new javax.swing.JButton();
        MoverVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setForeground(new java.awt.Color(0, 153, 0));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_close_window_50px.png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 40, 40));

        botonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menux64.png"))); // NOI18N
        botonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMenuMouseClicked(evt);
            }
        });
        jPanel2.add(botonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        tituloCobranzaArriendo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        tituloCobranzaArriendo.setForeground(new java.awt.Color(255, 255, 255));
        tituloCobranzaArriendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCobranzaArriendo.setText("Cobranza de arriendo");
        jPanel2.add(tituloCobranzaArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 90));

        idArriendoText.setBackground(new java.awt.Color(51, 153, 255));
        idArriendoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(idArriendoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 360, 40));

        netoText.setBackground(new java.awt.Color(51, 153, 255));
        netoText.setForeground(new java.awt.Color(255, 255, 255));
        netoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netoTextActionPerformed(evt);
            }
        });
        netoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                netoTextKeyReleased(evt);
            }
        });
        jPanel2.add(netoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 360, 40));

        ivaText.setBackground(new java.awt.Color(51, 153, 255));
        ivaText.setForeground(new java.awt.Color(255, 255, 255));
        ivaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaTextActionPerformed(evt);
            }
        });
        jPanel2.add(ivaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 360, 40));

        totalText.setBackground(new java.awt.Color(51, 153, 255));
        totalText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(totalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 360, 40));

        idEstadoCobranzaText.setBackground(new java.awt.Color(51, 153, 255));
        idEstadoCobranzaText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(idEstadoCobranzaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 360, 40));

        fechaRegistroText.setBackground(new java.awt.Color(51, 153, 255));
        fechaRegistroText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fechaRegistroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 360, 40));

        usuarioRegistroText.setBackground(new java.awt.Color(51, 153, 255));
        usuarioRegistroText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(usuarioRegistroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 360, 40));

        botonRealizarCobranza.setText("Realizar Cobranza");
        jPanel2.add(botonRealizarCobranza, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 290, 30));

        MoverVentana.setBackground(new java.awt.Color(102, 51, 255));
        MoverVentana.setForeground(new java.awt.Color(102, 51, 255));
        MoverVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverVentanaMouseDragged(evt);
            }
        });
        MoverVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverVentanaMousePressed(evt);
            }
        });
        jPanel2.add(MoverVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 620));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1320, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1070, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void MoverVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMouseDragged
        int cordenadaX = evt.getXOnScreen();
        int cordenadaY = evt.getYOnScreen();

        this.setLocation(cordenadaX-mouseX, cordenadaY-mouseY);
    }//GEN-LAST:event_MoverVentanaMouseDragged

    private void MoverVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MoverVentanaMousePressed

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void ivaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaTextActionPerformed

    private void netoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netoTextActionPerformed

    private void botonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuMouseClicked
        this.dispose();
        menuAdmin menuAdmn = new menuAdmin();
        menuAdmn.setVisible(true);
    }//GEN-LAST:event_botonMenuMouseClicked

    private void netoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_netoTextKeyReleased
        double neto,iva,total;
        neto = Double.parseDouble(netoText.getText());
        iva = neto*0.19;
        ivaText.setText(String.valueOf(iva));
        total = iva+neto;
        totalText.setText(String.valueOf(total));
    }//GEN-LAST:event_netoTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cobranzaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cobranzaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cobranzaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cobranzaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cobranzaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JLabel MoverVentana;
    private javax.swing.JLabel botonMenu;
    private javax.swing.JButton botonRealizarCobranza;
    private javax.swing.JTextField fechaRegistroText;
    private javax.swing.JTextField idArriendoText;
    private javax.swing.JTextField idEstadoCobranzaText;
    private javax.swing.JTextField ivaText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField netoText;
    private javax.swing.JLabel tituloCobranzaArriendo;
    private javax.swing.JTextField totalText;
    private javax.swing.JTextField usuarioRegistroText;
    // End of variables declaration//GEN-END:variables
}
