package vista;

import controlador.ConnectDB;
import java.awt.Component;
import controlador.TextPrompt;
import java.sql.*;
import javax.swing.JOptionPane;
import controlador.Qsql;

/**
 *
 * @author Nico
 */
public class Login extends javax.swing.JFrame {


int mouseX;
int mouseY;

    public Login() {
        initComponents();
        
        TextPrompt usuario = new TextPrompt("Ingrese usuario",IngresoUsuario);
        TextPrompt contraseña = new TextPrompt("••••••••••••••••",IngresoContraseña);
        this.setTitle("Rent A Car");
        this.setLocationRelativeTo(null);
              
                 
    }

   
    @Override
    public void setLocationRelativeTo(Component c) {
        super.setLocationRelativeTo(c); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        InicioSesionTitulo = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JLabel();
        IngresoUsuario = new javax.swing.JTextField();
        ContraseñaText = new javax.swing.JLabel();
        IngresoContraseña = new javax.swing.JPasswordField();
        BotonCerrar = new javax.swing.JButton();
        botonIniciarSesion = new javax.swing.JButton();
        UserIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MoverVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioSesionTitulo.setBackground(new java.awt.Color(51, 51, 51));
        InicioSesionTitulo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        InicioSesionTitulo.setForeground(new java.awt.Color(51, 51, 51));
        InicioSesionTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InicioSesionTitulo.setText("Inicio Sesión");
        InicioSesionTitulo.setToolTipText("");
        jPanel4.add(InicioSesionTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 620, 68));

        UsuarioText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        UsuarioText.setForeground(new java.awt.Color(51, 51, 51));
        UsuarioText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UsuarioText.setText("Usuario");
        jPanel4.add(UsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 127, -1));

        IngresoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        IngresoUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        IngresoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        IngresoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IngresoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoUsuarioActionPerformed(evt);
            }
        });
        jPanel4.add(IngresoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 300, 440, 62));

        ContraseñaText.setBackground(new java.awt.Color(0, 0, 0));
        ContraseñaText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ContraseñaText.setForeground(new java.awt.Color(51, 51, 51));
        ContraseñaText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ContraseñaText.setText("Contraseña");
        jPanel4.add(ContraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 159, -1));

        IngresoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        IngresoContraseña.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        IngresoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        IngresoContraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IngresoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoContraseñaActionPerformed(evt);
            }
        });
        jPanel4.add(IngresoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 420, 440, 62));

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setForeground(new java.awt.Color(0, 153, 0));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_close_window_50px.png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        jPanel4.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 40, 40));

        botonIniciarSesion.setBackground(new java.awt.Color(0, 153, 0));
        botonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciarSesion.setText("Iniciar Sesion");
        botonIniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        botonIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        jPanel4.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 530, 180, 30));

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/UserLogin - copia.png"))); // NOI18N
        jPanel4.add(UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 260));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 450, 640));

        MoverVentana.setBackground(new java.awt.Color(102, 51, 255));
        MoverVentana.setForeground(new java.awt.Color(102, 51, 255));
        MoverVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverVentanaMouseDragged(evt);
            }
        });
        MoverVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverVentanaMousePressed(evt);
            }
        });
        jPanel4.add(MoverVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -6, 1070, 630));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 620));

        setSize(new java.awt.Dimension(1069, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoContraseñaActionPerformed
       
    }//GEN-LAST:event_IngresoContraseñaActionPerformed

    private void MoverVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMouseDragged
        int cordenadaX = evt.getXOnScreen();
        int cordenadaY = evt.getYOnScreen();
        
        this.setLocation(cordenadaX-mouseX, cordenadaY-mouseY);
    }//GEN-LAST:event_MoverVentanaMouseDragged

    private void MoverVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MoverVentanaMousePressed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void IngresoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoUsuarioActionPerformed

    }//GEN-LAST:event_IngresoUsuarioActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
    Qsql conu = new Qsql();
    
    if(conu.validarLogin()==1){
        this.dispose();
        menuAdmin menuAdmn = new menuAdmin();
        menuAdmn.setVisible(true);
        JOptionPane.showMessageDialog(null, "Bienvenido "+IngresoUsuario.getText()+"");
    }else{
        JOptionPane.showMessageDialog(null,"Ingrese usuario y contraseña correctamente!","Error inicio sesión", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JLabel ContraseñaText;
    public static javax.swing.JPasswordField IngresoContraseña;
    public static javax.swing.JTextField IngresoUsuario;
    private javax.swing.JLabel InicioSesionTitulo;
    private javax.swing.JLabel MoverVentana;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UsuarioText;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    
}
