/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import javax.swing.JOptionPane;
/**
 *
 * @author Nico
 */
public class menuAdmin extends javax.swing.JFrame {
    int mouseX;
    int mouseY;
    /**
     * Creates new form Vista2
     */
    public menuAdmin() {
        initComponents();
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        tituloInicio = new javax.swing.JLabel();
        tituloAdministrador = new javax.swing.JLabel();
        botonRegistrarCliente = new javax.swing.JLabel();
        botonRegistrarVehiculo = new javax.swing.JLabel();
        botonArrendarVehiculo = new javax.swing.JLabel();
        botonCobranzaVehiculo = new javax.swing.JLabel();
        botonAgregarUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MoverVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setForeground(new java.awt.Color(0, 153, 0));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_close_window_50px.png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 40, 40));

        tituloInicio.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        tituloInicio.setForeground(new java.awt.Color(255, 255, 255));
        tituloInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloInicio.setText("Inicio");
        jPanel2.add(tituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 100));

        tituloAdministrador.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        tituloAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        tituloAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloAdministrador.setText("Administrador");
        jPanel2.add(tituloAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 1070, 100));

        botonRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregarCleintex128.png"))); // NOI18N
        botonRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarClienteMouseClicked(evt);
            }
        });
        jPanel2.add(botonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 130, 130));

        botonRegistrarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregarAutox128.png"))); // NOI18N
        botonRegistrarVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarVehiculoMouseClicked(evt);
            }
        });
        jPanel2.add(botonRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        botonArrendarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ArriedoCarx128.png"))); // NOI18N
        botonArrendarVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonArrendarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonArrendarVehiculoMouseClicked(evt);
            }
        });
        jPanel2.add(botonArrendarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, -1, -1));

        botonCobranzaVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cobranzax128.png"))); // NOI18N
        botonCobranzaVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCobranzaVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCobranzaVehiculoMouseClicked(evt);
            }
        });
        jPanel2.add(botonCobranzaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 160, -1, -1));

        botonAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadirUsuariox128.png"))); // NOI18N
        botonAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarUsuarioMouseClicked(evt);
            }
        });
        jPanel2.add(botonAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrar");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehiculo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Arriendo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Devolución");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cobranza");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vehiculo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agregar");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Usuario");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, -1, -1));

        MoverVentana.setBackground(new java.awt.Color(102, 51, 255));
        MoverVentana.setForeground(new java.awt.Color(102, 51, 255));
        MoverVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverVentanaMouseDragged(evt);
            }
        });
        MoverVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverVentanaMousePressed(evt);
            }
        });
        jPanel2.add(MoverVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 620));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1320, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1070, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void MoverVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMouseDragged
        int cordenadaX = evt.getXOnScreen();
        int cordenadaY = evt.getYOnScreen();

        this.setLocation(cordenadaX-mouseX, cordenadaY-mouseY);
    }//GEN-LAST:event_MoverVentanaMouseDragged

    private void MoverVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MoverVentanaMousePressed

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void botonRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarClienteMouseClicked
        registroCliente regc = new registroCliente();
        
        this.dispose();
        regc.setVisible(true);
       
    }//GEN-LAST:event_botonRegistrarClienteMouseClicked

    private void botonRegistrarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarVehiculoMouseClicked
        registroVehiculo regv = new registroVehiculo();
        this.dispose();
        regv.setVisible(true);
    }//GEN-LAST:event_botonRegistrarVehiculoMouseClicked

    private void botonArrendarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonArrendarVehiculoMouseClicked
        arrendarVehiculo arrv = new arrendarVehiculo();
        this.dispose();
        arrv.setVisible(true);
    }//GEN-LAST:event_botonArrendarVehiculoMouseClicked

    private void botonCobranzaVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCobranzaVehiculoMouseClicked
        cobranzaVehiculo cobv = new cobranzaVehiculo();
        this.dispose();
        cobv.setVisible(true);
    }//GEN-LAST:event_botonCobranzaVehiculoMouseClicked

    private void botonAgregarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarUsuarioMouseClicked
        crearCuenta crec = new crearCuenta();
        this.dispose();
        crec.setVisible(true);
    }//GEN-LAST:event_botonAgregarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JLabel MoverVentana;
    private javax.swing.JLabel botonAgregarUsuario;
    private javax.swing.JLabel botonArrendarVehiculo;
    private javax.swing.JLabel botonCobranzaVehiculo;
    private javax.swing.JLabel botonRegistrarCliente;
    private javax.swing.JLabel botonRegistrarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel tituloAdministrador;
    private javax.swing.JLabel tituloInicio;
    // End of variables declaration//GEN-END:variables
}
