/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import AppPackage.AnimationClass;
import controlador.TextPrompt;
import javax.swing.JOptionPane;
import controlador.Qsql;

/**
 *
 * @author Nico
 */
public class registroCliente extends javax.swing.JFrame {

    int mouseX;
    int mouseY;

    /**
     * Creates new form Vista2
     */
    public registroCliente() {
        initComponents();

        Qsql qsql = new Qsql();

        TextPrompt nombresIngreso = new TextPrompt("Nombres", nombreText);
        TextPrompt apellidosIngreso = new TextPrompt("Apellidos", apellidoText);
        TextPrompt rutIngreso = new TextPrompt("RUT (sin guión)", rutText);
        TextPrompt dvIngreso = new TextPrompt("Digito verificador", DVText);
        TextPrompt emailIngreso = new TextPrompt("e-mail", emailText);
        TextPrompt telefonoIngreso = new TextPrompt("Número de teléfono", telefonoText);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        botonMenu = new javax.swing.JLabel();
        tituloRegistrarCliente1 = new javax.swing.JLabel();
        botonRegistroCliente = new javax.swing.JLabel();
        tituloRegistrarCliente = new javax.swing.JLabel();
        idClienteText = new javax.swing.JTextField();
        rutText = new javax.swing.JTextField();
        nombreText = new javax.swing.JTextField();
        apellidoText = new javax.swing.JTextField();
        DVText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        telefonoText = new javax.swing.JTextField();
        botonRegistrarCliente = new javax.swing.JButton();
        botonBuscarCliente = new javax.swing.JButton();
        botonModificarCliente = new javax.swing.JButton();
        MoverVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setForeground(new java.awt.Color(0, 153, 0));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_close_window_50px.png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 40, 40));

        botonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menux64.png"))); // NOI18N
        botonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMenuMouseClicked(evt);
            }
        });
        jPanel2.add(botonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        tituloRegistrarCliente1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        tituloRegistrarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        tituloRegistrarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistrarCliente1.setText("Clientes");
        jPanel2.add(tituloRegistrarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 1070, 90));

        botonRegistroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregarCleintex64.png"))); // NOI18N
        botonRegistroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(botonRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        tituloRegistrarCliente.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        tituloRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        tituloRegistrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistrarCliente.setText("Registrar / Buscar / Modificar");
        jPanel2.add(tituloRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 90));

        idClienteText.setBackground(new java.awt.Color(0, 153, 0));
        idClienteText.setForeground(new java.awt.Color(0, 153, 0));
        idClienteText.setBorder(null);
        jPanel2.add(idClienteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, -1, -1));

        rutText.setBackground(new java.awt.Color(51, 153, 255));
        rutText.setForeground(new java.awt.Color(255, 255, 255));
        rutText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutTextActionPerformed(evt);
            }
        });
        jPanel2.add(rutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 360, 40));

        nombreText.setBackground(new java.awt.Color(51, 153, 255));
        nombreText.setForeground(new java.awt.Color(255, 255, 255));
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });
        jPanel2.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 360, 40));

        apellidoText.setBackground(new java.awt.Color(51, 153, 255));
        apellidoText.setForeground(new java.awt.Color(255, 255, 255));
        apellidoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTextActionPerformed(evt);
            }
        });
        jPanel2.add(apellidoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 360, 40));

        DVText.setBackground(new java.awt.Color(51, 153, 255));
        DVText.setForeground(new java.awt.Color(255, 255, 255));
        DVText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DVTextActionPerformed(evt);
            }
        });
        jPanel2.add(DVText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 360, 40));

        emailText.setBackground(new java.awt.Color(51, 153, 255));
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 360, 40));

        telefonoText.setBackground(new java.awt.Color(51, 153, 255));
        telefonoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(telefonoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 360, 40));

        botonRegistrarCliente.setText("Registrar");
        botonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(botonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 160, 30));

        botonBuscarCliente.setText("Buscar");
        botonBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarClienteMouseClicked(evt);
            }
        });
        jPanel2.add(botonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, 160, 30));

        botonModificarCliente.setText("Modificar");
        botonModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(botonModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 440, 160, 30));

        MoverVentana.setBackground(new java.awt.Color(102, 51, 255));
        MoverVentana.setForeground(new java.awt.Color(102, 51, 255));
        MoverVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverVentanaMouseDragged(evt);
            }
        });
        MoverVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverVentanaMousePressed(evt);
            }
        });
        jPanel2.add(MoverVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 624));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1320, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1070, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed

    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void MoverVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMouseDragged
        int cordenadaX = evt.getXOnScreen();
        int cordenadaY = evt.getYOnScreen();

        this.setLocation(cordenadaX - mouseX, cordenadaY - mouseY);
    }//GEN-LAST:event_MoverVentanaMouseDragged

    private void MoverVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MoverVentanaMousePressed

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked

        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Salir", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void DVTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DVTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DVTextActionPerformed

    private void rutTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutTextActionPerformed

    private void botonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuMouseClicked
        this.dispose();
        menuAdmin menuAdmn = new menuAdmin();
        menuAdmn.setVisible(true);
    }//GEN-LAST:event_botonMenuMouseClicked

    private void botonBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarClienteMouseClicked
        if (!rutText.getText().isEmpty()) {
        Qsql qsql = new Qsql();
        qsql.buscarCliente();
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese rut");
        }

    }//GEN-LAST:event_botonBuscarClienteMouseClicked

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void botonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarClienteActionPerformed
        if (!nombreText.getText().isEmpty() && !apellidoText.getText().isEmpty() && !rutText.getText().isEmpty() && !DVText.getText().isEmpty()
                && !emailText.getText().isEmpty() && !telefonoText.getText().isEmpty()) {
            Qsql qsql = new Qsql();
            qsql.registrarCliente();
        } else {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
        }
        
    }//GEN-LAST:event_botonRegistrarClienteActionPerformed

    private void apellidoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTextActionPerformed

    private void botonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarClienteActionPerformed
        Qsql qsql = new Qsql();
        qsql.modificarCliente();
    }//GEN-LAST:event_botonModificarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    public static javax.swing.JTextField DVText;
    private javax.swing.JLabel MoverVentana;
    public static javax.swing.JTextField apellidoText;
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JLabel botonMenu;
    private javax.swing.JButton botonModificarCliente;
    private javax.swing.JButton botonRegistrarCliente;
    private javax.swing.JLabel botonRegistroCliente;
    public static javax.swing.JTextField emailText;
    public static javax.swing.JTextField idClienteText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField nombreText;
    public static javax.swing.JTextField rutText;
    public static javax.swing.JTextField telefonoText;
    private javax.swing.JLabel tituloRegistrarCliente;
    private javax.swing.JLabel tituloRegistrarCliente1;
    // End of variables declaration//GEN-END:variables
}
