/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import AppPackage.AnimationClass;
import controlador.Qsql;
import controlador.TextPrompt;
import javax.swing.JOptionPane;
/**
 *
 * @author Nico
 */
public class registroVehiculo extends javax.swing.JFrame {
    int mouseX;
    int mouseY;
    /**
     * Creates new form Vista2
     */
    public registroVehiculo() {
        initComponents();
        
        Qsql qsql = new Qsql();
        qsql.datosVehiculos();
       
        
        

        TextPrompt modelo = new TextPrompt("Modelo",modeloText);
        TextPrompt año = new TextPrompt("Año",añoText);  
        TextPrompt cilindrada = new TextPrompt("Cilindrada",cilindradaText);
        TextPrompt patente= new TextPrompt("Patente",patenteText);
        TextPrompt valorArriendo = new TextPrompt("Valor arriendo",valorArriendoText);
        TextPrompt kilometrajeActual = new TextPrompt("Kilometraje actual",kilometrajeActText);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JButton();
        botonMenu = new javax.swing.JLabel();
        tituloRegistrarVehiculo = new javax.swing.JLabel();
        idVehiculoText = new javax.swing.JTextField();
        marcaCB = new javax.swing.JComboBox<>();
        idMarcaText = new javax.swing.JTextField();
        tipoVehiculoCB = new javax.swing.JComboBox<>();
        idTipoVehiculoText = new javax.swing.JTextField();
        tipoCarroceriaCB = new javax.swing.JComboBox<>();
        idTipoCarroceriaText = new javax.swing.JTextField();
        colorCB = new javax.swing.JComboBox<>();
        idColorText = new javax.swing.JTextField();
        estadoVehiculoCB = new javax.swing.JComboBox<>();
        idEstadoVehiculoText = new javax.swing.JTextField();
        patenteText = new javax.swing.JTextField();
        modeloText = new javax.swing.JTextField();
        añoText = new javax.swing.JTextField();
        cilindradaText = new javax.swing.JTextField();
        valorArriendoText = new javax.swing.JTextField();
        kilometrajeActText = new javax.swing.JTextField();
        botonRegistrarVehiculo = new javax.swing.JButton();
        botonBuscarVehiculo = new javax.swing.JButton();
        botonModificarVehiculo = new javax.swing.JButton();
        MoverVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setForeground(new java.awt.Color(0, 153, 0));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_close_window_50px.png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
        });
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 40, 40));

        botonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menux64.png"))); // NOI18N
        botonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMenuMouseClicked(evt);
            }
        });
        jPanel2.add(botonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        tituloRegistrarVehiculo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        tituloRegistrarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        tituloRegistrarVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistrarVehiculo.setText("Registrar / Buscar / Modificar");
        jPanel2.add(tituloRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 90));

        idVehiculoText.setBackground(new java.awt.Color(0, 153, 0));
        idVehiculoText.setForeground(new java.awt.Color(0, 153, 0));
        idVehiculoText.setBorder(null);
        jPanel2.add(idVehiculoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 20, -1));

        marcaCB.setBackground(new java.awt.Color(51, 153, 255));
        marcaCB.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(marcaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 360, 40));

        idMarcaText.setBackground(new java.awt.Color(0, 153, 0));
        idMarcaText.setForeground(new java.awt.Color(0, 153, 0));
        idMarcaText.setBorder(null);
        jPanel2.add(idMarcaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 30, -1));

        tipoVehiculoCB.setBackground(new java.awt.Color(51, 153, 255));
        tipoVehiculoCB.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tipoVehiculoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 360, 40));

        idTipoVehiculoText.setBackground(new java.awt.Color(0, 153, 0));
        idTipoVehiculoText.setForeground(new java.awt.Color(0, 153, 0));
        idTipoVehiculoText.setBorder(null);
        jPanel2.add(idTipoVehiculoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 30, -1));

        tipoCarroceriaCB.setBackground(new java.awt.Color(51, 153, 255));
        tipoCarroceriaCB.setForeground(new java.awt.Color(255, 255, 255));
        tipoCarroceriaCB.setBorder(null);
        tipoCarroceriaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCarroceriaCBActionPerformed(evt);
            }
        });
        jPanel2.add(tipoCarroceriaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 360, 40));

        idTipoCarroceriaText.setBackground(new java.awt.Color(0, 153, 0));
        idTipoCarroceriaText.setForeground(new java.awt.Color(0, 153, 0));
        idTipoCarroceriaText.setBorder(null);
        jPanel2.add(idTipoCarroceriaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 30, -1));

        colorCB.setBackground(new java.awt.Color(51, 153, 255));
        colorCB.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(colorCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 360, 40));

        idColorText.setBackground(new java.awt.Color(0, 153, 0));
        idColorText.setForeground(new java.awt.Color(0, 153, 0));
        idColorText.setBorder(null);
        jPanel2.add(idColorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 30, -1));

        estadoVehiculoCB.setBackground(new java.awt.Color(51, 153, 255));
        estadoVehiculoCB.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(estadoVehiculoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 360, 40));

        idEstadoVehiculoText.setBackground(new java.awt.Color(0, 153, 0));
        idEstadoVehiculoText.setForeground(new java.awt.Color(0, 153, 0));
        idEstadoVehiculoText.setBorder(null);
        jPanel2.add(idEstadoVehiculoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 190, 30, -1));

        patenteText.setBackground(new java.awt.Color(51, 153, 255));
        patenteText.setForeground(new java.awt.Color(255, 255, 255));
        patenteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patenteTextActionPerformed(evt);
            }
        });
        jPanel2.add(patenteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 360, 40));

        modeloText.setBackground(new java.awt.Color(51, 153, 255));
        modeloText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(modeloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 360, 40));

        añoText.setBackground(new java.awt.Color(51, 153, 255));
        añoText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(añoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 360, 40));

        cilindradaText.setBackground(new java.awt.Color(51, 153, 255));
        cilindradaText.setForeground(new java.awt.Color(255, 255, 255));
        cilindradaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cilindradaTextActionPerformed(evt);
            }
        });
        jPanel2.add(cilindradaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 360, 40));

        valorArriendoText.setBackground(new java.awt.Color(51, 153, 255));
        valorArriendoText.setForeground(new java.awt.Color(255, 255, 255));
        valorArriendoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorArriendoTextActionPerformed(evt);
            }
        });
        jPanel2.add(valorArriendoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 360, 40));

        kilometrajeActText.setBackground(new java.awt.Color(51, 153, 255));
        kilometrajeActText.setForeground(new java.awt.Color(255, 255, 255));
        kilometrajeActText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilometrajeActTextActionPerformed(evt);
            }
        });
        jPanel2.add(kilometrajeActText, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 360, 40));

        botonRegistrarVehiculo.setText("Registrar");
        botonRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(botonRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 160, 30));

        botonBuscarVehiculo.setText("Buscar");
        botonBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(botonBuscarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 460, 160, 30));

        botonModificarVehiculo.setText("Modificar");
        botonModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(botonModificarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 160, 30));

        MoverVentana.setBackground(new java.awt.Color(102, 51, 255));
        MoverVentana.setForeground(new java.awt.Color(102, 51, 255));
        MoverVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoverVentanaMouseDragged(evt);
            }
        });
        MoverVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoverVentanaMousePressed(evt);
            }
        });
        jPanel2.add(MoverVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1070, 620));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1320, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1070, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void MoverVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMouseDragged
        int cordenadaX = evt.getXOnScreen();
        int cordenadaY = evt.getYOnScreen();

        this.setLocation(cordenadaX-mouseX, cordenadaY-mouseY);
    }//GEN-LAST:event_MoverVentanaMouseDragged

    private void MoverVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoverVentanaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MoverVentanaMousePressed

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void cilindradaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cilindradaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cilindradaTextActionPerformed

    private void botonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenuMouseClicked
        this.dispose();
        menuAdmin menuAdmn = new menuAdmin();
        menuAdmn.setVisible(true);
    }//GEN-LAST:event_botonMenuMouseClicked

    private void patenteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patenteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patenteTextActionPerformed

    private void valorArriendoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorArriendoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorArriendoTextActionPerformed

    private void kilometrajeActTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilometrajeActTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kilometrajeActTextActionPerformed

    private void tipoCarroceriaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCarroceriaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCarroceriaCBActionPerformed

    private void botonRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVehiculoActionPerformed
        Qsql qsql = new Qsql();
        qsql.registrarVehiculo();
    }//GEN-LAST:event_botonRegistrarVehiculoActionPerformed

    private void botonBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarVehiculoActionPerformed
       Qsql qsql = new Qsql();
       qsql.buscarVehiculos();
    }//GEN-LAST:event_botonBuscarVehiculoActionPerformed

    private void botonModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarVehiculoActionPerformed
        Qsql qsql = new Qsql();
        qsql.modificarVehiculo();
    }//GEN-LAST:event_botonModificarVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JLabel MoverVentana;
    public static javax.swing.JTextField añoText;
    private javax.swing.JButton botonBuscarVehiculo;
    private javax.swing.JLabel botonMenu;
    private javax.swing.JButton botonModificarVehiculo;
    private javax.swing.JButton botonRegistrarVehiculo;
    public static javax.swing.JTextField cilindradaText;
    public static javax.swing.JComboBox<String> colorCB;
    public static javax.swing.JComboBox<String> estadoVehiculoCB;
    public static javax.swing.JTextField idColorText;
    public static javax.swing.JTextField idEstadoVehiculoText;
    public static javax.swing.JTextField idMarcaText;
    public static javax.swing.JTextField idTipoCarroceriaText;
    public static javax.swing.JTextField idTipoVehiculoText;
    public static javax.swing.JTextField idVehiculoText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField kilometrajeActText;
    public static javax.swing.JComboBox<String> marcaCB;
    public static javax.swing.JTextField modeloText;
    public static javax.swing.JTextField patenteText;
    public static javax.swing.JComboBox<String> tipoCarroceriaCB;
    public static javax.swing.JComboBox<String> tipoVehiculoCB;
    private javax.swing.JLabel tituloRegistrarVehiculo;
    public static javax.swing.JTextField valorArriendoText;
    // End of variables declaration//GEN-END:variables
}
